drivers: soc: oplus: uboot_log: Fix kthread_run() usage with correct thread function signature
kthread_run() requires a function with the prototype 'int (void *)',
but ubootback_thread_fn was incorrectly defined as 'int (void)'.
This caused a build failure with -Wincompatible-function-pointer-types.
Error fixed :- drivers/soc/oplus/system/uboot_log/uboot_log.c:204:33: error: incompatible function pointer types passing 'int (void)' to parameter of type 'int (*)(void *)' [-Wincompatible-function-pointer-types]
  204 |         ubootback_thread = kthread_run(ubootback_thread_fn, NULL, "ubootback_thread");
      |                                        ^~~~~~~~~~~~~~~~~~~
../include/linux/kthread.h:49:20: note: expanded from macro 'kthread_run'
   49 |                 = kthread_create(threadfn, data, namefmt, ## __VA_ARGS__); \
      |                                  ^~~~~~~~
../include/linux/kthread.h:26:25: note: expanded from macro 'kthread_create'
   26 |         kthread_create_on_node(threadfn, data, NUMA_NO_NODE, namefmt, ##arg)
      |                                ^~~~~~~~
../include/linux/kthread.h:9:50: note: passing argument to parameter 'threadfn' here
    9 | struct task_struct *kthread_create_on_node(int (*threadfn)(void *data),
      |                                                  ^
1 error generated.
Fixed by updating ubootback_thread_fn to accept a void * argument
as required by the kernel thread API.

Signed-off-by: <cyberDay777> <asacademybhind@gmail.com>