healthinfo: Fix incorrect path to fg_uid.h header
Fixes build error caused by incorrect include path:
fatal error: '../fs/fg_uid/fg_uid.h' file not found

Updated the include path to point to the correct location:
fs/proc/healthinfo/fg_uid/fg_uid.h

Error:-In file included from ../include/soc/oplus/healthinfo.h:17:
../include/linux/healthinfo/fg.h:5:10: fatal error: '../fs/fg_uid/fg_uid.h' file not found
    5 | #include "../fs/fg_uid/fg_uid.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~